import esbuild from 'esbuild';
import { gzipSync } from 'node:zlib';
import { builtinModules } from 'node:module';
import { readFile, writeFile } from 'node:fs/promises';
import process from 'node:process';

const manifest = JSON.parse(await readFile('manifest.json', 'utf8'));
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD FOR SELFGROW ${manifest.version}.
*/`;

const production = process.argv[2] === 'production';
const maximumProductEntryBytes = 750 * 1024;
const nodeBuiltins = new Set([
  ...builtinModules,
  ...builtinModules.map((name) => `node:${name}`),
  'electron',
]);

function assertMobileImports(metafile) {
  const forbiddenImports = [];

  for (const [inputPath, input] of Object.entries(metafile.inputs)) {
    for (const imported of input.imports) {
      if (nodeBuiltins.has(imported.path)) {
        forbiddenImports.push(`${inputPath} -> ${imported.path}`);
      }
    }
  }

  if (forbiddenImports.length > 0) {
    throw new Error(`Mobile runtime imports are forbidden:\n${forbiddenImports.join('\n')}`);
  }
}

const context = await esbuild.context({
  banner: { js: banner },
  bundle: true,
  entryPoints: ['src/main.ts'],
  external: [
    'obsidian',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
  ],
  format: 'cjs',
  logLevel: 'info',
  metafile: true,
  minify: production,
  outfile: 'main.js',
  platform: 'browser',
  sourcemap: production ? false : 'inline',
  target: 'es2021',
  treeShaking: true,
});

if (production) {
  const result = await context.rebuild();
  assertMobileImports(result.metafile);
  await context.dispose();

  const output = await readFile('main.js');
  const gzipBytes = gzipSync(output).byteLength;

  if (output.byteLength > maximumProductEntryBytes) {
    throw new Error(
      `Product-entry main.js is ${output.byteLength} bytes, above the ${maximumProductEntryBytes}-byte budget.`,
    );
  }

  await writeFile(
    'build-meta.json',
    `${JSON.stringify(
      {
        bytes: output.byteLength,
        gzipBytes,
        esbuild: result.metafile,
      },
      null,
      2,
    )}\n`,
  );

  console.log(`Production bundle: ${output.byteLength} bytes (${gzipBytes} bytes gzip).`);
} else {
  await context.watch();
}
